import { Chord_Variant } from '@/types';

export const CHORD_INFO: Record<Chord_Variant, { symbol: string; display: string }> = {
	major: { symbol: '', display: 'Major' },
	minor: { symbol: 'm', display: 'Minor' },
	diminished: { symbol: 'dim', display: 'Diminished' },
	augmented: { symbol: 'aug', display: 'Augmented' },
	sus2: { symbol: 'sus2', display: 'Suspended 2 (sus2)' },
	sus4: { symbol: 'sus4', display: 'Suspended 4 (sus4)' },
	'power-chord': { symbol: '5', display: 'Power Chord (5)' },
	add9: { symbol: 'add9', display: 'Add 9 (add9)' },
	'minor-add9': { symbol: 'madd9', display: 'Minor Add 9' },
	'major-6': { symbol: '6', display: 'Major 6 (6)' },
	'minor-6': { symbol: 'm6', display: 'Minor 6' },
	'dominant-7': { symbol: '7', display: 'Dominant 7 (7)' },
	'major-7': { symbol: 'maj7', display: 'Major 7' },
	'minor-7': { symbol: 'm7', display: 'Minor 7' },
	'minor-major-7': { symbol: 'mM7', display: 'Minor Major 7' },
	'half-diminished-7': { symbol: 'ø7', display: 'Half Diminished 7 (ø7)' },
	'diminished-7': { symbol: 'dim7', display: 'Diminished 7 (dim7)' },
	'augmented-7': { symbol: 'aug7', display: 'Augmented 7 (aug7)' },
	'dominant-9': { symbol: '9', display: 'Dominant 9 (9)' },
	'major-9': { symbol: 'maj9', display: 'Major 9' },
	'minor-9': { symbol: 'm9', display: 'Minor 9' },
	'dominant-11': { symbol: '11', display: 'Dominant 11 (11)' },
	'major-11': { symbol: 'maj11', display: 'Major 11' },
	'minor-11': { symbol: 'm11', display: 'Minor 11' },
	'dominant-13': { symbol: '13', display: 'Dominant 13 (13)' },
	'major-13': { symbol: 'maj13', display: 'Major 13' },
	'minor-13': { symbol: 'm13', display: 'Minor 13' },
	'dominant-7-flat-5': { symbol: '7♭5', display: 'Dominant 7 Flat 5 (7♭5)' },
	'dominant-7-sharp-5': { symbol: '7♯5', display: 'Dominant 7 Sharp 5 (7♯5)' },
	'dominant-7-flat-9': { symbol: '7♭9', display: 'Dominant 7 Flat 9 (7♭9)' },
	'dominant-7-sharp-9': { symbol: '7♯9', display: 'Dominant 7 Sharp 9 (7♯9)' },
	'dominant-7-sharp-11': { symbol: '7♯11', display: 'Dominant 7 Sharp 11 (7♯11)' },
	'dominant-7-flat-13': { symbol: '7♭13', display: 'Dominant 7 Flat 13 (7♭13)' },
	'major-7-flat-5': { symbol: 'maj7♭5', display: 'Major 7 Flat 5 (maj7♭5)' },
	'major-7-sharp-5': { symbol: 'maj7♯5', display: 'Major 7 Sharp 5 (maj7♯5)' },
} as const;
